// src/data.js
const transactions = [
  { customerId: 1, month: "January", amount: 120 },
  { customerId: 1, month: "January", amount: 80 },
  { customerId: 2, month: "January", amount: 150 },
  { customerId: 1, month: "January", amount: 120 },
  { customerId: 1, month: "January", amount: 80 },
  { customerId: 2, month: "January", amount: 150 },
  { customerId: 1, month: "February", amount: 200 },
  { customerId: 2, month: "February", amount: 100 },
  { customerId: 1, month: "March", amount: 90 },
  { customerId: 3, month: "March", amount: 120 },
  { customerId: 2, month: "April", amount: 180 },
  { customerId: 3, month: "April", amount: 110 },
  { customerId: 4, month: "May", amount: 120 },
  { customerId: 3, month: "May", amount: 80 },
  { customerId: 2, month: "June", amount: 150 },
  { customerId: 2, month: "June", amount: 200 },
  { customerId: 4, month: "June", amount: 100 },
  { customerId: 2, month: "July", amount: 90 },
  { customerId: 1, month: "July", amount: 120 },
  { customerId: 5, month: "August", amount: 110 },
  { customerId: 3, month: "September", amount: 110 },
  { customerId: 4, month: "September", amount: 150 },
  { customerId: 3, month: "September", amount: 110 },
  { customerId: 5, month: "September", amount: 150 },
  { customerId: 3, month: "October", amount: 110 },
  { customerId: 2, month: "October", amount: 100 },
  { customerId: 2, month: "October", amount: 150 },
  { customerId: 1, month: "December", amount: 120 },
  { customerId: 5, month: "December", amount: 180 },
  { customerId: 3, month: "December", amount: 110 },
];

export default transactions;
